org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.java.home=E:/Foxaria-main/.jdks/jdk-21.0.11+10
org.gradle.java.installations.paths=C:/Users/alexf/AppData/Roaming/.minecraft/runtime/java-runtime-delta/windows/java-runtime-delta,E:/Foxaria-main/.jdks/jdk-21.0.11+10
