rootProject.name = 'foxaria'

include 'foxaria-api'
include 'foxaria-core'
include 'foxaria-economy'
include 'foxaria-kits'
include 'foxaria-cases'
include 'foxaria-cases-bukkit'
include 'foxaria-cases-proxy'
include 'foxaria-shop'
include 'foxaria-donate-shop'
include 'foxaria-auction'
include 'foxaria-ranks'
include 'foxaria-store'
include 'foxaria-moderation'
include 'foxaria-admin'
include 'foxaria-security'
include 'foxaria-custom-items'
include 'foxaria-retention'
include 'foxaria-auth'
include 'foxaria-guilds'
include 'foxaria-item-templates'
include 'foxaria-regions'
include 'foxaria-crafting'
include 'foxaria-modern-furnace'
include 'foxaria-bootstrap'
include 'foxaria-proxy-bungee'
include 'foxaria-hub-guard'
